# app/observability/metrics.py

from opentelemetry import metrics
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.exporter.prometheus import PrometheusMetricReader
from opentelemetry.sdk.resources import Resource


SERVICE_NAME = "enterprise-ai-assistant"
METER_NAME = SERVICE_NAME


meter = None

# ==========================================================
# Agent
# ==========================================================

agent_requests = None
agent_failures = None
agent_duration_seconds = None

# ==========================================================
# LLM
# ==========================================================

llm_calls = None
llm_duration_seconds = None

llm_input_tokens = None
llm_output_tokens = None
llm_total_tokens = None

# ==========================================================
# Tools
# ==========================================================

tool_calls = None
tool_failures = None
tool_duration_seconds = None

# ==========================================================
# Memory
# ==========================================================

memory_retrieval = None
memory_retrieval_duration_seconds = None

memory_extraction = None
memory_extraction_duration_seconds = None

memory_created = None


_metrics_configured = False


def configure_metrics() -> None:
    global _metrics_configured
    global meter

    global agent_requests
    global agent_failures
    global agent_duration_seconds

    global llm_calls
    global llm_duration_seconds
    global llm_input_tokens
    global llm_output_tokens
    global llm_total_tokens

    global tool_calls
    global tool_failures
    global tool_duration_seconds

    global memory_retrieval
    global memory_retrieval_duration_seconds

    global memory_extraction
    global memory_extraction_duration_seconds

    global memory_created

    if _metrics_configured:
        return

    resource = Resource.create(
        {
            "service.name": SERVICE_NAME,
        }
    )

    # Prometheus scrapes metrics from /metrics.
    reader = PrometheusMetricReader()

    provider = MeterProvider(
        resource=resource,
        metric_readers=[reader],
    )

    metrics.set_meter_provider(provider)

    meter = metrics.get_meter(
        METER_NAME
    )

    # ==================================================
    # Agent metrics
    # ==================================================

    agent_requests = meter.create_counter(
        name="agent_requests",
        description="Total number of agent requests",
        unit="1",
    )

    agent_failures = meter.create_counter(
        name="agent_failures",
        description="Total number of failed agent requests",
        unit="1",
    )

    agent_duration_seconds = meter.create_histogram(
        name="agent_duration_seconds",
        description="Agent request duration",
        unit="s",
    )

    # ==================================================
    # LLM metrics
    # ==================================================

    llm_calls = meter.create_counter(
        name="llm_calls",
        description="Total number of LLM calls",
        unit="1",
    )
    llm_input_tokens = meter.create_counter(
        name="llm_input_tokens",
        description="Total number of input tokens sent to LLMs",
        unit="token",
    )

    llm_output_tokens = meter.create_counter(
        name="llm_output_tokens",
        description="Total number of output tokens generated by LLMs",
        unit="token",
    )

    llm_total_tokens = meter.create_counter(
        name="llm_total_tokens",
        description="Total number of input and output tokens",
        unit="token",
    )

    llm_duration_seconds = meter.create_histogram(
        name="llm_duration_seconds",
        description="LLM call duration",
        unit="s",
    )

    # ==================================================
    # Tool metrics
    # ==================================================

    tool_calls = meter.create_counter(
        name="tool_calls",
        description="Total number of tool calls",
        unit="1",
    )

    tool_failures = meter.create_counter(
        name="tool_failures",
        description="Total number of failed tool calls",
        unit="1",
    )

    tool_duration_seconds = meter.create_histogram(
        name="tool_duration_seconds",
        description="Tool execution duration",
        unit="s",
    )

    # ==================================================
    # Memory retrieval
    # ==================================================

    memory_retrieval = meter.create_counter(
        name="memory_retrieval",
        description="Total number of memory retrieval operations",
        unit="1",
    )

    memory_retrieval_duration_seconds = (
        meter.create_histogram(
            name="memory_retrieval_duration_seconds",
            description="Memory retrieval duration",
            unit="s",
        )
    )

    # ==================================================
    # Memory extraction
    # ==================================================

    memory_extraction = meter.create_counter(
        name="memory_extraction",
        description="Total number of memory extraction operations",
        unit="1",
    )

    memory_extraction_duration_seconds = (
        meter.create_histogram(
            name="memory_extraction_duration_seconds",
            description="Memory extraction duration",
            unit="s",
        )
    )

    # ==================================================
    # Memory creation
    # ==================================================

    memory_created = meter.create_counter(
        name="memory_created",
        description="Total number of memories created",
        unit="1",
    )

    _metrics_configured = True
