"""add run id to approval requests

Revision ID: 73e217f36638
Revises: afce69245e82
Create Date: 2026-08-25 11:27:17.131070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e217f36638'
down_revision: Union[str, Sequence[str], None] = 'afce69245e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('run_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_approval_requests_run_id'), 'approval_requests', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_run_id'), table_name='approval_requests')
    op.drop_column('approval_requests', 'run_id')
    # ### end Alembic commands ###
